export const languages = {
  en: {
    welcome: "Welcome",
    toggle: "Switch Language",
    loading: "Loading Astronomy Picture of the Day...",
    error: "Error",
    back: "BACK",
    week01: "Week 01",
    week02: "Week 02",
    week02Title: "Week 02 Exercises",
    home: "Home",
    exercise01: "Exercise 01",
    exercise02: "Exercise 02",
    exercise03: "Exercise 03",
    exercise04: "Exercise 04",
    blogsTitle: "Blogs",
    readMore: "Read More",
    backToExercise03: "Back to Exercise03",
    loadingEpic: "Loading EPIC image for",
    pleaseProvideDate:
      "Please provide a date query parameter, e.g. ?date=2023-07-01",
    nasaEpicTitle: "NASA EPIC Image for",
    errorPrefix: "Error:",
    exercise03Title: "Exercise 3 - Navigation",
    sampleBlogPost: "Sample Blog Post",
  },
  es: {
    welcome: "Bienvenido",
    toggle: "Cambiar idioma",
    loading: "Cargando la Imagen Astronómica del Día...",
    error: "Error",
    back: "VOLVER",
    week01: "Semana 01",
    week02: "Semana 02",
    week02Title: "Ejercicios Semana 02",
    home: "Inicio",
    exercise01: "Ejercicio 01",
    exercise02: "Ejercicio 02",
    exercise03: "Ejercicio 03",
    exercise04: "Ejercicio 04",
    blogsTitle: "Blogs",
    readMore: "Leer más",
    backToExercise03: "Volver a Ejercicio03",
    loadingEpic: "Cargando imagen EPIC para",
    pleaseProvideDate:
      "Por favor proporcione un parámetro de fecha, por ejemplo ?date=2023-07-01",
    nasaEpicTitle: "Imagen NASA EPIC para",
    errorPrefix: "Error:",
    exercise03Title: "Ejercicio 3 - Navegación",
    sampleBlogPost: "Entrada de blog de ejemplo",
  },
  ur: {
    welcome: "خوش آمدید",
    toggle: "زبان تبدیل کریں",
    loading: "دن کی فلکی تصویر لوڈ ہو رہی ہے...",
    error: "خرابی",
    back: "پیچھے",
    week01: "ہفتہ 01",
    week02: "ہفتہ 02",
    week02Title: "ہفتہ 02 کی مشقیں",
    home: "ہوم",
    exercise01: "مشک نمبر 01",
    exercise02: "مشک نمبر 02",
    exercise03: "مشک نمبر 03",
    exercise04: "مشک نمبر 04",
    blogsTitle: "بلاگز",
    readMore: "مزید پڑھیں",
    backToExercise03: "واپس Exercise03 پر جائیں",
    loadingEpic: "EPIC تصویر لوڈ ہو رہی ہے",
    pleaseProvideDate:
      "براہ کرم تاریخ کا سوالی پیرامیٹر فراہم کریں، مثال کے طور پر ?date=2023-07-01",
    nasaEpicTitle: "NASA EPIC تصویر برائے",
    errorPrefix: "خرابی:",
    exercise03Title: "مشک 3 - نیویگیشن",
    sampleBlogPost: "مثال بلاگ پوسٹ",
  },
  da: {
    welcome: "Velkommen",
    toggle: "Skift sprog",
    loading: "Indlæser Dagens Astronomiske Billede...",
    error: "Fejl",
    back: "TILBAGE",
    week01: "Uge 01",
    week02: "Uge 02",
    week02Title: "Uge 02 Øvelser",
    home: "Hjem",
    exercise01: "Øvelse 01",
    exercise02: "Øvelse 02",
    exercise03: "Øvelse 03",
    exercise04: "Øvelse 04",
    blogsTitle: "Blogs",
    readMore: "Læs mere",
    backToExercise03: "Tilbage til Øvelse03",
    loadingEpic: "Indlæser EPIC billede for",
    pleaseProvideDate:
      "Angiv en dato som forespørgselsparameter, f.eks. ?date=2023-07-01",
    nasaEpicTitle: "NASA EPIC billede for",
    errorPrefix: "Fejl:",
    exercise03Title: "Øvelse 3 - Navigation",
    sampleBlogPost: "Eksempel Blogindlæg",
  },
};
